-- Must be using SYS user

-- Create a tablespace for the garage
CREATE TABLESPACE GARAGE
  DATAFILE 'garage.dbf'
  SIZE 100M
  AUTOEXTEND ON
  NEXT 10M;

-- Create a user for the garage
CREATE USER GARAGEUSER IDENTIFIED BY your_password;

-- Grant the user some privileges
ALTER USER GARAGEUSER DEFAULT TABLESPACE GARAGE;
ALTER USER GARAGEUSER ACCOUNT UNLOCK;
GRANT CREATE SESSION TO GARAGEUSER;
GRANT CREATE TABLE TO GARAGEUSER ; 
GRANT CREATE TRIGGER TO GARAGEUSER; 
GRANT CREATE SEQUENCE TO GARAGEUSER;
GRANT CREATE VIEW TO GARAGEUSER;
ALTER USER GARAGEUSER QUOTA UNLIMITED ON GARAGE;

